on: [push]

jobs:
  test_vpns:
    runs-on: ubuntu-latest
    name: Testing VPNs
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v1
      - uses: docker/build-push-action@v2
        with:
          context: .
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: ghcr.io/heig-srx-2023/srx-labo-5:latest
          push: true
#      - name: Build docker
#        run: docker-compose build
#      - name: Show docker images before test
#        run: docker images
      - name: Pull docker
        run: docker pull ghcr.io/heig-srx-2023/srx-labo-5
      - name: Test VPNs
        run: test/runit.sh
#      - name: Show docker images after test
#        run: docker images
